### ISSUE TITLE
Separate WebHID consent per vendor

### ISSUE THREAD

**Issue by Draginfable** [purecloudlabs/softphone-vendor-headsets#103]
With the current implementation when **requestDevice** is called for a specific vendor/device, the filters are populated with **usage** and **usagePage**.

```
const filters = [{ usage: HEADSET_USAGE, usagePage: HEADSET_USAGE_PAGE }];
await (window.navigator as any).hid.requestDevice({ filters });
```

It would be very useful/user-friendly, if **vendorId** was also provided in the filters, so that the user only has to chose between related devices.
Likewise, since the flow is triggered by a user's attempt to select a specific device, the **productId** could also be added on the filters. 

Looking forward to hearing your thoughts. Thank you. 

EDIT:
I see that the vendorId is actually used in CyberAcoustics implementation, and the jabra module also does this automatically. So it would be better if the implementations are as consistent as possible. 

EDIT 2:
I have created a pull request: https://github.com/purecloudlabs/softphone-vendor-headsets/pull/104

**Comment by Draginfable** [comment]
Hello @jensengar, @maxwellmooney13,

Thank you for taking the time to review the PR. I'm really glad you like it. 
Do you have any plans on when you are going to run the next release?

**Comment by maxwellmooney13** [comment]
Hi @Draginfable right now nothing concrete but I'm working on something myself so hopefully I can get that done really quick and then we can include your changes in that upcoming release.  Thank you again for working on this.

**Comment by Draginfable** [comment]
I have just tested the latest release and everything seems to be working fine. Thank you!
